# Header

menu:
  主页: /
  归档: /archives/

# SubNav
subnav:
  github: "https://github.com/"
  #weibo: "#"
  #rss: "#"
  #zhihu: "#"
  #qq: "#"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  #mail: "mailto:wangxiaohui0821@gmail.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: 

# Content

# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: true
# 是否在新窗口打开链接
open_in_new: false

# 打赏
# 请在需要打赏的文章的md文件头部，设置属性reward: true

# 打赏基础设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 2
# 打赏wording
reward_wording: '感谢您的点滴相助'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: 
# 微信二维码图片地址
weixin: 

# Miscellaneous
baidu_analytics: ''
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: http://hzoi-mafia.github.io/4342.png
#是否开启分享
share_jia: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus 不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: true

#2、网易云跟帖
wangyiyun: true

#3、畅言
changyan_appid: true
changyan_conf: true

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: true

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
  #innerArchive: false
smart_menu:
  innerArchive: '全部文章'
  friends: '友链'
  aboutme: '关于我'

#innerArchive: false

friends:
  我神奇的同桌hww: http://www.cnblogs.com/Maplers/
  各种援助我建博客的大佬WXH: http://wildrage.cf/
  大佬WQ: http://www.cnblogs.com/TSHugh/
  又一个大佬ZZH: http://www.cnblogs.com/LadyLex/
  某自己有服务器的壕YZH: https://zhuohao.me
  756最帅的ryf: http://blog.csdn.net/ren_ivan/
  小姨子xyz: http://www.cnblogs.com/radioteletscope/
  zyf_2002: http://blog.csdn.net/zyf_2002
  interesting_byb: http://www.cnblogs.com/Loser-of-Life/
  Hallmeow's blog: http://blog.csdn.net/hallmeow
  hyy大佬: http://www.cnblogs.com/FOXYY/
  ljm大佬: http://blog.csdn.net/h_anonymity
  QTY's blog: http://blog.csdn.net/qty2001
  一哥QSY: http://www.cnblogs.com/forevergoodboy/
  mk(quan kai)大佬: http://www.cnblogs.com/A-LEAF

aboutme: <br>funny<br>学生党<br>不想滚去高考的OIer<br>OW&SCⅡ忠实玩家